[project]
name = "basic-erc20"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mamushi>=0.1.0",
    "titanoboa>=0.2.8",
]
